---
name: Build and Release Go Application

on: # yamllint disable-line rule:truthy
  release:
    types:
      - created

jobs:
  build:
    name: Build Go Application
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Get Release Version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Build for multiple platforms
        run: |
          mkdir -p dist
          GOOS=linux GOARCH=amd64 go build -ldflags "-X main.version=${{ env.VERSION }}" -o dist/GoBillIt-${{ env.VERSION }}-linux-amd64 ./cmd/GoBillIt
          GOOS=darwin GOARCH=amd64 go build -ldflags "-X main.version=${{ env.VERSION }}" -o dist/GoBillIt-${{ env.VERSION }}-darwin-amd64 ./cmd/GoBillIt
          GOOS=windows GOARCH=amd64 go build -ldflags "-X main.version=${{ env.VERSION }}" -o dist/GoBillIt-${{ env.VERSION }}-windows-amd64.exe ./cmd/GoBillIt

      - name: Upload release assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/GoBillIt-${{ env.VERSION }}-linux-amd64
            dist/GoBillIt-${{ env.VERSION }}-darwin-amd64
            dist/GoBillIt-${{ env.VERSION }}-windows-amd64.exe

  docker:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/gobillit:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/gobillit:${{ github.event.release.tag_name }}
